 services:
- type: web
name: ambassador-automator-backend
env: python
plan: starter
region: oregon
buildCommand: pip install -r requirements.txt
startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
envVars:
- key: MONGO_URI
sync: false
- key: N8N_BASE_URL
sync: false
- key: N8N_BEARER_TOKEN
sync: false
- key: CLICKBANK_SECRET
sync: false
- key: OPENAI_API_KEY
sync: false
- key: TELEGRAM_BOT_TOKEN
sync: false
- key: CLOUDINARY_KEY
sync: false
	
